name: CI Workflow with Unit Tests and Codecov

on:
  push:
    branches: [ "main", "object_detection_navigation" ]
  pull_request:
    branches: [ "main", "object_detection_navigation" ]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    defaults:
      run:
        shell: bash  # Use bash for shell commands

    container:
      image: osrf/ros:humble-desktop  # Use ROS Humble from Docker Hub

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies and fix empy installation
      - name: Install system dependencies and fix empy issue
        run: |
          # Install system dependencies
          sudo apt update
          sudo apt install -y doxygen lcov gcovr

      # Step 3: Build and run unit tests, generate coverage report
      - name: Build, run unit tests, and generate coverage report
        run: |
          # Build the project
          rm -rf build install
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug
          
          # Run tests and generate the coverage data
          colcon test
          lcov --directory build/ --capture --output-file build/test_coverage_merged.info

      # Step 4: Upload coverage result to Codecov
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Required for private repositories
          files: ${{ github.workspace }}/build/test_coverage_merged.info
          fail_ci_if_error: true  # Fail the CI if there are any errors
          verbose: true  # Show detailed information in the log
