name: CI Workflow

on:
  push:
    branches: ["main", "object_detection_navigation"] 
  pull_request:
    branches: ["main", "object_detection_navigation"] 
      

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up ROS environment (for ROS2)
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          ros-distro: humble

      # Step 3: Install dependencies (including lcov, if not already installed)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov python3-pip
          pip install --upgrade pip
          sudo apt-get install -y python3-colcon-common-extensions

      # Step 4: Build the project
      - name: Build the project
        run: |
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug

      # Step 5: Run tests
      - name: Run tests and collect coverage data
        run: |
          colcon test 
          lcov --directory build/ --capture --output-file build/test_coverage.info
          
        # genhtml build/test_coverage.info --output-directory build/coverage-report

      # Step 6: Upload coverage data to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Required for private repositories
          files: ${{github.workspace}}/build/test_coverage.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          disable_search: true # optional (default = false)
          plugin: none         # optional (xcode, gcov, pycoverage)
