name: CI Workflow with Unit Tests and Codecov

on:
  push:
    branches: [ "main", "object_detection_navigation" ]
  pull_request:
    branches: [ "main", "object_detection_navigation" ]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    defaults:
      run:
        shell: bash  # Use bash for shell commands

    container:
      image: osrf/ros:humble-desktop  # Use ROS Humble from Docker Hub

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install system packages
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr

      # Install ROS 2 and dependencies
      - name: Install ROS 2 dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ros-humble-ament-cmake \
            ros-humble-rosidl-typesupport-c \
            ros-humble-rosidl-generator-c \
            ros-humble-builtin-interfaces \
            ros-humble-std-msgs \
            python3-pip
          # Install Python dependencies for ament package support
          python3 -m pip install --upgrade setuptools
          python3 -m pip install ament-package

      # Step 3: Build the project and run unit tests
      - name: Build, run unit tests, and generate coverage report
        run: |
          # Build the project
          rm -rf build install
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug
          
          # Run tests and generate the coverage data
          colcon test
          lcov --directory build/ --capture --output-file build/test_coverage_merged.info

      # Step 4: Upload coverage results to Codecov
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Required for private repositories
          files: ${{ github.workspace }}/build/test_coverage_merged.info
          fail_ci_if_error: true  # Fail the CI if there are any errors
          verbose: true  # Show detailed information in the log
